# 指定运行端口
server:
  port: 8101

# 指定服务名称
spring:
  application:
    name: neo4j-service
  neo4j:
    authentication:
      username: xxx
      password: xxx
    uri: bolt://xxx

eureka:
  instance:
    # 服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 90
    # 服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 30
  client:
    # 注册到Eureka的注册中心
    register-with-eureka: true
    # 获取注册实例列表
    fetch-registry: true
    # 30s重新从服务中心获取实例列表
    registry-fetch-interval-seconds: 30
    service-url:
      # 配置注册中心地址
      defaultZone: http://root:root@localhost:8001/eureka/